name: lab3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql_flutter: ^3.1.0
  provider: ^4.3.2+2
  flutter_icons: ^1.1.0
  flutter_dotenv: ^2.1.0
  number_display: ^2.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/media/
    - .env

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira_Sans/FiraSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fira_Sans/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLight.ttf
          weight: 200
    - family: SansitaSwashed
      fonts:
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sansita_Swashed/SansitaSwashed-Light.ttf
          weight: 300
